version: "3"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_HOST: 127.0.0.1
  hf:
    image: hfapp
    restart: always
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
